---
entryPoints:
  web:
    address: ":80"

  websecure:
    address: ":443"
    
api:
  insecure: true
  dashboard: true
    
global:
  checkNewVersion: true
  sendAnonymousUsage: false
  
    
certificatesResolvers:
  production:
    acme:
      email: Eric.G.Greene@hotmail.com
      storage: /etc/etraefik/certs/prod-acme.json
      httpChallenge:
        entryPoint: web
  staging:
    acme:
      email: Eric.G.Greene@hotmail.com
      storage: /etc/etraefik/certs/non-prod-acme.json
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      httpChallenge:
        entryPoint: web

providers:
  file:
    directory: /etc/etraefik/config
    watch: true

experimental:
  plugins:
    torblock:
      moduleName: "github.com/jpxd/torblock"
      version: "v0.1.1"
      
    log4shell:
      moduleName: "github.com/traefik/plugin-log4shell"
      version: "v0.1.2"