---
entryPoints:
  http:
    address: :80

  https:
    address: :443
    
api:
  insecure: true
  dashboard: true
    
global:
  checkNewVersion: true
  sendAnonymousUsage: true
    
#certificatesResolvers:
#  letsencrypt:
#    acme:
#      email: "Eric.G.Greene@hotmail.com"
#      storage: /etc/etraefik/certs/acme.json
#      httpChallenge:
#        entryPoint: http

providers:
  file:
    directory: /etc/etraefik/config
    watch: true

#experimental:
#  plugins:
#    torblock:
#      moduleName: "github.com/jpxd/torblock"
#      version: "v0.1.1"
      
#    log4shell:
#      moduleName: "github.com/traefik/plugin-log4shell"
#      version: "v0.1.2"