---
entryPoints:
  web:
    address: :80
#    http:
#      redirections:
#        entryPoint:
#          to: https
#          scheme: https
  websecure:
    address: :443
    
api:
  insecure: true
  dashboard: true
    
global:
  checkNewVersion: true
  sendAnonymousUsage: false
  
# (Optional) Log information
# ---
log:
  level: DEBUG  # DEBUG, INFO, WARNING, ERROR, CRITICAL
    format: common  # common, json, logfmt
    filePath: /etc/etraefik/traefik.log

# (Optional) Accesslog
# ---
accesslog:
   format: common  # common, json, logfmt
   filePath: /etc/etraefik/access.log
    
certificatesResolvers:
#  production:
#    acme:
#      email: Eric.G.Greene@hotmail.com
#      storage: /etc/etraefik/certs/prod-acme.json
#      httpChallenge:
#        entryPoint: web
  staging:
    acme:
      email: Eric.G.Greene@hotmail.com
      storage: /etc/etraefik/certs/non-prod-acme.json
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      httpChallenge:
        entryPoint: web

#  cloudflare-resolver:
#    acme:
#      email: "Eric.G.Greene@hotmail.com"
#      storage: /etc/etraefik/certs/acme.json
#      dnsChallenge:
#        provider: "cloudflare"
#          CF_API_EMAIL: 
#            - Eric.G.Greene@hotmail.com
#          CF_API_KEY: 
#            - A4xck34t7BOS3Ju8vIzUfN0QGhM50SqI55go7UyZ
#            resolvers:
#              - 1.1.1.1:53
#              - 8.8.8.8:53







# Configure your CertificateResolver here...
# ---
# certificatesResolvers:
#   staging:
#     acme:
#       email: your-email@example.com
#       storage: /etc/traefik/certs/acme.json
#       caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
#       httpChallenge:
#         entryPoint: web
#
#   production:
#     acme:
#       email: your-email@example.com
#       storage: /etc/traefik/certs/acme.json
#       caServer: "https://acme-v02.api.letsencrypt.org/directory"
#       httpChallenge:
#         entryPoint: web

# (Optional) Overwrite Default Certificates
# tls:
#   stores:
#     default:
#       defaultCertificate:
#         certFile: /etc/traefik/certs/cert.pem
#         keyFile: /etc/traefik/certs/cert-key.pem
# (Optional) Disable TLS version 1.0 and 1.1
#   options:
#     default:
#       minVersion: VersionTLS12







          
          

providers:
  file:
    directory: /etc/etraefik/config
    watch: true

experimental:
  plugins:
    torblock:
      moduleName: "github.com/jpxd/torblock"
      version: "v0.1.1"
      
    log4shell:
      moduleName: "github.com/traefik/plugin-log4shell"
      version: "v0.1.2"