---
entryPoints:
  ssl-http:
    address: :80
#    http:
#      redirections:
#        entryPoint:
#          to: https
#          scheme: https

    
api:
  insecure: true
  dashboard: true
    
global:
  checkNewVersion: true
  sendAnonymousUsage: false
    
certificatesResolvers:
#  letsencrypt-prod:
#    acme:
#      email: "Eric.G.Greene@hotmail.com"
#      storage: /etc/etraefik/certs/acme.json
#      httpChallenge:
#        entryPoint: ssl-http
  letsencryptStaging:
    acme:
      email: "Eric.G.Greene@hotmail.com"
      storage: /etc/etraefik/certs/acme.json
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      httpChallenge:
        entryPoint: ssl-http
      
#  cloudflare-resolver:
#    acme:
#      email: "Eric.G.Greene@hotmail.com"
#      storage: /etc/etraefik/certs/acme.json
#      dnsChallenge:
#        provider: "cloudflare"
#          CF_API_EMAIL: 
#            - Eric.G.Greene@hotmail.com
#          CF_API_KEY: 
#            - A4xck34t7BOS3Ju8vIzUfN0QGhM50SqI55go7UyZ
#            resolvers:
#              - 1.1.1.1:53
#              - 8.8.8.8:53
          
          

providers:
  file:
    directory: /etc/etraefik/config
    watch: true

experimental:
  plugins:
    torblock:
      moduleName: "github.com/jpxd/torblock"
      version: "v0.1.1"
      
    log4shell:
      moduleName: "github.com/traefik/plugin-log4shell"
      version: "v0.1.2"