---
http:
  middlewares:
    log4shell:
      plugin:
        log4shell:
          errorCode: 200

    torblock:
      plugin:
        torblock:
          AddressListURL: https://check.torproject.org/exit-addresses
          Enabled: "true"
          UpdateInterval: "3600"


#  routers:
#    to-jellyfin-Coitus:
#      rule: "Host(`jellyfin.coitus.io`)"
#      middlewares:
#        - log4shell
#        - torblock
#      service: jellyfin
        

      
    to-jellyfin-Coitus-secure:
      rule: "Host(`jellyfin.coitus.io`)"
      middlewares:
        - log4shell
        - torblock
        - https_redirect
      service: jellyfin
      
#      tls:
#        certResolver: letsencrypt

        

        
  services:
    jellyfin:
      loadBalancer:
        servers:
          - url: http://10.0.1.6:8096