---
http:
  routers:
    to-jellyfin-Coitus-secure:
      entryPoints:
        - http
        - https
      rule: "Host(`jellyfin.coitus.io`)"
      middlewares:
        - secured@file
      service: jellyfin
      tls:
        certResolver: letsencryptStaging

    to-jellyfin-Coitus-Local-secure:
      entryPoints:
        - http
        - https
      rule: "Host(`jellyfin.coitus.local`)"
      middlewares:
        - secured@file
      service: jellyfin
#      tls:
#        certResolver: letsencryptStaging


  services:
    jellyfin:
      loadBalancer:
        servers:
          - url: http://10.0.1.6:8096