---
http:
  middlewares:
    log4shell:
      plugin:
        log4shell:
          errorCode: 200

    torblock:
      plugin:
        torblock:
          AddressListURL: https://check.torproject.org/exit-addresses
          Enabled: "true"
          UpdateInterval: "3600"

    redirect:
      redirectScheme:
        scheme: https
        permanent: true
        port: "443"


#  routers:
#    to-jellyfin-Coitus:
#      rule: "Host(`jellyfin.coitus.io`)"
#      middlewares:
#        - log4shell
#        - torblock
#        - https-redirect
#      service: jellyfin
        

      
    to-jellyfin-Coitus-secure:
      rule: "Host(`jellyfin.coitus.io`)"
      middlewares:
        - redirect
        - log4shell
        - torblock
      service: jellyfin
      
#      tls:
#        certResolver: letsencrypt

#    to-jellyfin-8bitshit:
#      rule: "Host(`jellyfin.8bitshit.com`)"
#      service: jellyfin

#    to-jellyfin-8bitshit-secure:
#      rule: "Host(`jellyfin.8bitshit.com`)"
#      service: jellyfin
#      tls:
#        certResolver: letsencrypt
        

        
  services:
    jellyfin:
      loadBalancer:
        servers:
          - url: http://10.0.1.6:8096