---
http:
  routers:

    to-jellyfin-Coitus-secure:
      entryPoints:
       - websecure
      rule: "Host(`jellyfin.coitus.io`)"
      middlewares:
       - secured@file
       - https-redirect@file
      service: jellyfin
      tls:
        certResolver: staging

  services:
    jellyfin:
      loadBalancer:
        servers:
          - url: http://10.0.1.6:8096
          
