---
http:


  routers:
    to-jellyfin-Coitus:
      entrypoints: 
      - http
      rule: "Host(`jellyfin.coitus.io`)"
      middlewares:
        - secured@file
#        - torblock
#        - https_redirect
      service: jellyfin

    to-jellyfin-Coitus-secure:
      entrypoints: 
      - https
      rule: "Host(`jellyfin.coitus.io`)"
      middlewares:
        - secured@file
#        - log4shell
#        - torblock
      service: jellyfin
#      tls:
#        certResolver: letsencrypt
        
  services:
    jellyfin:
      loadBalancer:
        servers:
          - url: http://10.0.1.6:8096