---
http:


  routers:

#    to-jellyfin-Coitus:
#      entrypoints: 
#      - http
#      - https
#      rule: "Host(`jellyfin.coitus.io`)"
#      middlewares:
#        - secured@file
#      service: jellyfin

    to-jellyfin-Coitus-secure:
      entrypoints: 
      - http
      - https
      rule: "Host(`jellyfin.coitus.io`)"
      middlewares:
        - secured@file
      service: jellyfin
#      tls:
#        certResolver: letsencrypt
        
  services:
    jellyfin:
      loadBalancer:
        servers:
          - url: 10.0.1.6:8096/