---
http:
  routers:
  
    to-jellyfin-Coitus:
      entryPoints:
        - web
      rule: "Host(`coitus.io`)"
      middlewares:
        - secured@file
      service: jellyfin
      tls:
        certResolver: staging
  
    to-jellyfin-Coitus-secure:
      entryPoints:
        - web
        - websecure
      rule: "Host(`jellyfin.coitus.io`)"
      middlewares:
        - secured@file
      service: jellyfin
      tls:
        certResolver: staging

    to-jellyfin-Coitus-Local-secure:
      entryPoints:
        - web
        - websecure
      rule: "Host(`jellyfin.coitus.local`)"
      middlewares:
        - secured@file
      service: jellyfin
#      tls:
#        certResolver: staging
    to-jellyfin-Coitus-Local:
      entryPoints:
        - web
      rule: "Host(`jellyfin.coitus.local`)"
      middlewares:
        - secured@file
      service: jellyfin
#      tls:
#        certResolver: staging


  services:
    jellyfin:
      loadBalancer:
        servers:
          - url: http://10.0.1.6:8096