---
http:


  routers:
    to-plexia-Coitus:
      entrypoints: 
      - http
      rule: "Host(`plexia.coitus.io`)"
      middlewares:
#        - secured@file
      service: plexia

    to-plexia-Coitus-secure:
      entrypoints: 
      - https
      rule: "Host(`plexia.coitus.io`)"
      middlewares:
#        - secured@file
      service: plexia
#      tls:
#        certResolver: letsencrypt
        
  services:
    plexia:
      loadBalancer:
        servers:
          - url:http://10.0.1.5:32400